from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'business.views.index', name="index"), 
    url(r'^get_bus_business/$', 'business.views.get_bus_business',name="get_bus_business"), 
    url(r'^add_bus_business/$', 'business.views.add_bus_business',name="add_bus_business"),
    url(r'^delete_bus_business/$', 'business.views.delete_bus_business',name="delete_bus_business"), 
    url(r'^one_business/(?P<business>\w+)/$','business.views.one_business', name="one_business"),
    url(r'^show_pos/(?P<business>\w+)/$','business.views.show_pos', name="show_pos"),
    url(r'^delete_src/$','business.views.delete_src', name="delete_src"),
    url(r'^add_src/$','business.views.add_src', name="add_src"),
    url(r'^delete_target/$','business.views.delete_target', name="delete_target"),
    url(r'^update_target/$','business.views.update_target', name="update_target"),
    url(r'^add_target/$','business.views.add_target', name="add_target"),
    url(r'^delete_bus/$','business.views.delete_bus', name="delete_bus"),
    url(r'^add_bus/$','business.views.add_bus', name="add_bus"),
    url(r'^modify_bus_user/$','business.views.modify_bus_user', name="modify_bus_user"),
    url(r'^add_task_src/$','business.views.add_task_src', name="add_task_src"),
    url(r'^modify_transfer_type/$','business.views.modify_transfer_type', name="modify_transfer_type"),
    url(r'^start_tran/$','business.views.start_tran', name="start_tran"),
    url(r'^stop_tran/$','business.views.stop_tran', name="stop_tran"),
    url(r'^bus_start/$','business.views.bus_start', name="bus_start"),
    url(r'^view_log/$','business.views.view_log', name="view_log"),
    url(r'^bus_stop/$','business.views.bus_stop', name="bus_stop"),
    url(r'^bus_info/$','business.views.bus_info', name="bus_info"),
    url(r'^modify_pos/$','business.views.modify_pos', name="modify_pos"),
    url(r'^modify_all_pos/$','business.views.modify_all_pos', name="modify_all_pos"),
    url(r'^modify_charset_type/$','business.views.modify_charset_type', name="modify_charset_type"),
    url(r'^set_target_count/$','business.views.set_target_count', name="set_target_count"),
    url(r'^modify_source_target_type/$','business.views.modify_source_target_type', name="modify_source_target_type"),
    url(r'^modify_bus_mon/$','business.views.modify_bus_mon', name="modify_bus_mon"),
    url(r'^add_schema/$', 'business.views.add_schema', name="add_schema"),
    url(r'^update_schema/$', 'business.views.update_schema', name="update_schema"),
    url(r'^remove_schema/$', 'business.views.remove_schema', name="remove_schema"),
    url(r'^modify_check_snapshot/$', 'business.views.modify_check_snapshot', name="modify_check_snapshot"),
    url(r'^modify_hbase_full_thread_num/$', 'business.views.modify_hbase_full_thread_num', name="modify_hbase_full_thread_num"),
)
